version: "3"
services:
  db:
    build: db
    ports:
      - "5432"
  java:
    build: .
    depends_on:
      - db
    ports:
      - "8081:8080"
    environment:
      - DB_CONN=jdbc:postgresql://db:5432/
    command: [ "./wait-for-it.sh", "db:5432", "-t", "0", "--", "java", "-jar", "App.jar" ]


